USE WASTE2MONEYDB;

DELIMITER $$
USE `WASTE2MONEYDB`$$

CREATE PROCEDURE `ClienAddorUpdate ` (
  IN _ID_CLIENTE INT,
  IN _NOMBRE VARCHAR(30),
  IN _TELEFONO VARCHAR(30),
  IN _DIRECCION VARCHAR(50),
  IN _ID_USUARIO INT,
  IN _ID_SCORE INT
)
BEGIN 
  IF _ID_CLIENTE = 0 THEN
    INSERT INTO TB_CLIENTE (NOMBRE, TELEFONO,DIRECCION, ID_USUARIO,ID_SCORE)
    VALUES (_NOMBRE, _TELEFONO,_ID_DIRECCION, _ID_USUARIO,_ID_SCORE);

    SET _ID_ADMIN = LAST_INSERT_ID();
  ELSE
    UPDATE TB_ADMIN
    SET
    NOMBRE = _NOMBRE,
    TELEFONO = _TELEFONO,
    DIRECCION = _DIRECCION,
    ID_USUARIO =_ID_USUARIO,
    ID_SCORE = _ID_SCORE
    WHERE ID_CLIENTE = _ID_CLIENTE;
  END IF;

  SELECT _ID_CLIENTE AS 'id';
END