USE WASTE2MONEYDB;

DELIMITER $$
USE `WASTE2MONEYDB`$$

CREATE PROCEDURE `ScoreAddorUpdate ` (
  IN _ID_SCORE INT,
  IN _PUNTUACION VARCHAR(30),
  IN _COLILLAS VARCHAR(30),
  IN _PUNTOS_TOTALES VARCHAR(50),
  IN _RECOMPENSAS INT  
)
BEGIN 
  IF _ID_SCORE = 0 THEN
    INSERT INTO TB_CLIENTE (PUNTUACION, COLILLAS,PUNTOS_TOTALES, RECOMPENSAS)
    VALUES (_PUNTUACION, _COLILLAS,_PUNTOS_TOTALES, _RECOMPENSAS);

    SET _ID_SCORE = LAST_INSERT_ID();
  ELSE
    UPDATE TB_SCORE
    SET
    PUNTUACION = _PUNTUACION,
    COLILLAS = _COLILLAS,
    PUNTOS_TOTALES = _PUNTOS_TOTALES,
    RECOMPENSAS =_RECOMPENSAS,    
    WHERE ID_SCORE = _ID_SCORE;
  END IF;

  SELECT _ID_SCORE AS 'id';
END